# Generated by Django 3.1.6 on 2021-02-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Required.Inform a valid email address.', max_length=200)),
                ('admission_year', models.CharField(max_length=200, null=True)),
                ('your_department', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('why_join_us', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
