# Generated by Django 3.1.6 on 2021-02-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Literarry_CLub', '0002_remove_customuserform_why_join_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserForm',
        ),
    ]
