# Generated by Django 3.1.6 on 2021-02-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Literarry_CLub', '0003_delete_customuserform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('admission_year', models.CharField(max_length=30)),
                ('your_department', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=13)),
                ('description', models.TextField()),
            ],
        ),
    ]
