# Generated by Django 3.1.3 on 2021-03-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Literarry_CLub', '0004_signupmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmodel',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
