# Generated by Django 3.1.3 on 2021-04-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Literarry_CLub', '0006_peptalksusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PepTalksUsers',
            new_name='PepTalksUserModel',
        ),
        migrations.RenameModel(
            old_name='SignUpModel',
            new_name='PragatishilModel',
        ),
    ]
